### ISSUE TITLE
[테스트 데이터 생성기] CH 02. CLIP 11. 데이터베이스: DB 접근용 repository 코드의 작성

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#13]
repository layer를 작성하여 실제로 쿼리를 날릴 수 있는 인터페이스를 마련한다.

## Todo

* [x] 가짜 데이터 repository
* [x] 테이블 스키마 repository
* [x] 스키마 필드 repository

## Reference

* https://spring.io/guides/gs/accessing-data-jpa
