### ISSUE TITLE
[테스트 데이터 생성기] CH 02. CLIP 13. 필요 기능을 제공할 api의 테스트 작성하기

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#15]
실제로 필요한 최소한의 기능을 확인하고, 이를 서빙할 api를 테스트를 작성하는 방법으로 설계한다.
이 작업은 클라이언트에게 오픈할 기능(API)의 입출력 스펙만을 다룬다. 실제 서비스 구현을 포함하지 않는다.
(ex: 스키마 출력하기 api 작업은 실제 `.csv` 파일 작성 기능을 하지는 않음)

내부 기능 구현은 별도 작업으로 진행될 예정.

## Todo

* [x] 특정 회원의 테이블 스키마 목록 조회하기 (검색, 정렬, 페이징을 고려) (기본 페이지로 사용할 수 있음)
* [x] 특정 회원의 단일 테이블 스키마 정보 조회하기
* [x] 특정 회원의 스키마 저장/수정/삭제하기
    * PRG 패턴 고려하기
    * `GET`, `POST`만 쓰는 이유 확인하기
* [x] 스키마 출력하기 (`.csv`, `.tsv`, `.json`, `.sql`)
* [x] 회원 정보 조회하기
* [x] 메인 페이지 설정하기

## Reference

* https://docs.spring.io/spring-boot/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.spring-mvc-tests
* https://en.wikipedia.org/wiki/Post/Redirect/Get
* https://www.baeldung.com/servlet-redirect-forward
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method
* https://softwareengineering.stackexchange.com/questions/114156/why-are-there-no-put-and-delete-methods-on-html-forms
