### ISSUE TITLE
[테스트 데이터 생성기] CH 03. CLIP 01. 뷰 만들기: 메인 페이지

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#18]
테스트 데이터 생성기 서비스의 메인 페이지가 될 테이블 스키마 뷰를 만든다.

## Todo

* [x] 헤더(header)는 GNB를 보여줘야 한다.
* [x] 스키마 페이지에서는 스키마를 작성할 수 있는 폼을 제공한다.
* [x] 시작 페이지는 스키마 작성 페이지를 로그인 유무 상관 없이 보여준다.
* [x] 푸터(footer)는 간단한 기본정보(연도, 서비스 이름 등)를 표시해야 한다.
* [ ] #59

## Reference

* https://tailwindcss.com/
* https://github.com/javve/list.js
* https://fontawesome.com/v5/search

**Comment by djkeh** [comment]
이 강의에서 마크업 뷰를 그리는 타임리프 템플릿 파일은 강의 계획에 따라 chatgpt를 사용하고 있으며, 과정이 자세하게 나오지 않습니다.
정확한 코드 변경은 pr #60 을 참고하세요.
