### ISSUE TITLE
[테스트 데이터 생성기] CH 03. CLIP 03. 뷰 만들기: 자료형 선택 화면

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#20]
이번 프로젝트에서 참고하고 있는 Mockaroo를 보면, 각 필드 자료형을 클릭할 때 큰 팝업을 볼 수 있다.
이를 구현하는 것을 검토한다.

## Todo

* [x] 관련 디자인 기술 조사하기
* [x] 구현이 필요한 기능 정리
    * 자료형을 모두 보여준다.
    * 자료형을 그룹별로 보여준다.
    * 자료형은 검색 가능해야 한다.
* [ ] 자료형 선택화면 구현 여부 의사결정

## Reference

* https://www.mockaroo.com/
* https://tailwindui.com/components/application-ui/overlays/modal-dialogs

**Comment by djkeh** [comment]
논의 끝에, 이 기능은 대부분 모달 팝업을 구현하는 디자인적 요소를 중심으로 개발될 것으로 예상하기 때문에,
우리 강의 취지에는 약간 맞지 않는 부분이 있는 것으로 판단하고, 개발 내용에서 제외하기로 함.
