### ISSUE TITLE
[테스트 데이터 생성기] CH 03. CLIP 05. 인증 기능: github OAuth 인증 구현

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#22]
#21 에서 학습한 내용을 상기하고, 본 서비스에 깃헙 OAuth 2.0 인증을 도입한다.

## Todo

* [x] 깃헙 OAuth Apps 등록하기
* [x] 깃헙 인증 연결하기
* [x] 깃헙 인증 데이터 설계하기
* [x] 설정 클래스 수정
* [x] 내 정보 페이지에 인증 정보 전달

## Reference

* https://spring.io/guides/tutorials/spring-boot-oauth2
* https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/oauth2.html#testing-oauth2-login
* https://docs.github.com/ko/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
* https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-the-authenticated-user
