### ISSUE TITLE
[테스트 데이터 생성기] CH 03. CLIP 19. 배포: 헤로쿠 연동

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#36]
헤로쿠에 서비스를 배포하여 CI/CD 를 완성하고 테스트 데이터 생성기를 웹서비스가 가능한 상태로 만든다.

## Todo

* [x] 헤로쿠 계정 등록
* [x] 2FA 인증 설정
* [x] 과금 정보 설정
* [ ] 새로운 헤로쿠 앱 구성하기
    * [ ] 다이노 설정
    * [x] 깃헙 저장소 연동
    * [x] DB로 사용할 JawsDB 애드 온 설치
    * [ ] 환경변수 설정
    * [ ] 배포

## Reference

* https://devcenter.heroku.com/articles/github-integration
* https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku
