### ISSUE TITLE
[테스트 데이터 생성기] CH 02. CLIP 05. 스프링 부트 프로젝트 초기화하기

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#5]
한글 테스트 데이터 자동 생성기 서비스를 만들기 위한 소스코드 바탕을 준비한다.

## Todo

* [x] Spring Initializr: 자바 21 + 스프링 부트 3.3 으로 프로젝트 시작하기
* [x] 자바 21: 경고 로그 원인 찾고 제거하기
    * Class data sharing (CDS) 경고
    * Dynamic loading of agents 경고
* [x] 기초 application properties 셋업
* [x] 미리 해둘 필요가 있는 기초 설정 코드 작성해두기
    * JPA
    * Security
* [x] #50

## Reference

* https://docs.oracle.com/en/java/javase/21/vm/class-data-sharing.html
* https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17
* https://belief-driven-design.com/looking-at-java-21-feature-deprecations-03fff/
* https://github.com/ryandens/javaagent-gradle-plugin
* https://docs.spring.io/spring-data/jpa/reference/auditing.html
* https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#jc-httpsecurity
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by djkeh** [comment]
## Update!

본 작업에 해당하는 온라인 강의 도중, 스프링 이니셜라이저(https://start.spring.io/) 스프링 부트 디펜던시 셋업을 할 때
`spring-boot-starter-oauth2-client`, `spring-boot-starter-thymeleaf`를 세팅할 경우
`thymeleaf-extras-springsecurity6`, `spring-security-test` 의존성은 함께 자동으로 따라오지 않기 때문에 따로 작성해 주어야 함을 언급드렸습니다.

이 문제가 오늘 부로 해결되었음을 공유드립니다.
자세한 내용은 아래를 참조하세요.

## Reference

* spring-io/start.spring.io#1542

**Comment by djkeh** [comment]
#50 작업이 추가되어 이슈를 다시 오픈함. #50 마무리되면 함께 닫을 것.
