### ISSUE TITLE
[테스트 데이터 생성기] CH 02. CLIP 06. 도메인 설계 1: 기본 회원 정보와 개인 스키마 저장 테이블

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#6]
테스트 데이터 생성기가 사용할 도메인 중, 회원과 스키마를 설계한다.

## Todo

* [x] ~~회원 도메인 설계 검토~~
* [x] 테이블 스키마 도메인 설계
    * 스키마 이름, 소유한 회원, 출력 여부
* [x] 스키마 필드 도메인 설계
    * 필드 이름, 자료형, 필드 순서, nullable 유무, 가짜 데이터 생성 옵션, 직접 입력

**Comment by djkeh** [comment]
논의 결과, 회원 정보는 우리가 서비스할 때 직접 저장할 필요가 없다고 판단했다. 따라서 이 단계에서 설계에 포함하지 않기로 하였다.
