### ISSUE TITLE
자료형 도메인 설계하기

### ISSUE THREAD

**Issue by djkeh** [djkeh/test-data#8]
가짜 데이터를 만들 때, 이는 특정한 자료형이 된다. (ex: 문자열, 숫자, 이름, 이메일, 전화번호, 자동차 등등)
이 자료형의 구조를 설계해서 자료형을 참조하면 해당 자료형에 알맞는 가짜 데이터를 생성할 수 있도록 기반을 만든다.

## Todo

* [x] 이것을 DB에 저장할 것인가?
* [x] 이름, 다양한 옵션값
    * 옵션이 필요 없는 경우
    * 커스텀 옵션: 키 밸류 형식으로 어떤 옵션이든 담아서 쓸 수 있는 형태
    * 숫자: 최대최소값, 소수점 여부(decimals)
    * 시간: 범위(`from` ~ `to`), 출력 형식
    * 일정한 규칙을 가진 고정 길이 문자열
    * 일정한 규칙을 가진 가변 길이 문자열
    * 문자열 데이터셋을 이용한 랜덤 생성 문장 (K lorem ipsum)
* [x] 다양한 자료형을 지원해야 한다.
* [x] ~~자료형은 검색해서 찾을 수 있어야 한다: 인덱스 고려~~

## Reference

* https://ko.wikipedia.org/wiki/로렘_입숨
* https://namu.wiki/w/로렘%20입숨

**Comment by djkeh** [comment]
논의 결과, 가짜 데이터의 자료형 도메인은 DB에 저장할 필요 없다는 결론. 따라서 enum으로 관리한다.

**Comment by djkeh** [comment]
가짜 데이터 자료형의 검색 기능은 추가 기능으로 고려하고, 일단 기본 구현 계획에서는 제외해서 프로젝트 계획을 단순하게 잡아보기로 결정했다.
